server:
  port: 8580
  forward-headers-strategy: framework
  servlet:
    context-path: "/api/library"
spring:
  application:
    name: library-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service
  data:
    mongodb:
      database: library
      auto-index-creation: true


eureka:
  instance:
    prefer-ip-address: true

keycloak:
  bearer-only: true