server:
  port: 8580
  forward-headers-strategy: framework
spring:
  application:
    name: library-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service
  data:
    mongodb:
      host: ${MONGO_DB_HOST_URL:127.0.0.1}
      port: ${MONGO_DB_HOST_PORT:27017}
      authentication-database: admin
      database: libray
      username: ${MONGO_DB_ROOT_USERNAME:admin}
      password: ${MONGO_DB_ROOT_PASSWORD:root}


eureka:
  instance:
    prefer-ip-address: true

keycloak:
  bearer-only: true