spring:
  application:
    name: course-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service
  data:
    mongodb:
      database: course-service

eureka:
  instance:
    prefer-ip-address: true

keycloak:
  bearer-only: true
server:
  port: 4001
  servlet:
    context-path: "/api/course"

