spring:
  application:
    name: gateway-service

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${AUTH_ROOT_URL:http://localhost:8180}/auth/realms/CollageERP
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: collage-erp-web
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**

        - id: exam-service
          uri: lb://EXAM-SERVICE
          predicates:
            - Path=/api/exam/**

        - id: library-service
          uri: lb://LIBRARY-SERVICE
          predicates:
            - Path=/api/library/**

        - id: user-interface-service
          uri: lb://UI-SERVICE
          predicates:
            - Path=/**


      default-filters:
        - TokenRelay

server:
  port: 8080
