spring:
  data:
    mongodb:
      host: ${MONGO_DB_HOST_URL:127.0.0.1}
      port: ${MONGO_DB_HOST_PORT:27017}
      authentication-database: admin
      database: user
      username: ${MONGO_DB_ROOT_USERNAME:admin}
      password: ${MONGO_DB_ROOT_PASSWORD:root}