spring:
  application:
    name: exam-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service
  data:
    mongodb:
      database: exam-service

server:
  port: 3081
  servlet:
    context-path: "/api/exam"